- Generell Problem der Höhe, Beispiel testfelder
- Alle Partner auf einen Screen. IDs vergeben, alle in weiß
- Gibt es die Fahrzeuge mit den ganzen Elementen als SVG? (also hotspots?)
  - am besten alle innerhalb des Bildrahmens
- Woher Benutzer bei Downloads?
  - 
